sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t maha205/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maha205/docker-react npm run test
