sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t maha205/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maha205/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-us-east-2-232409596377"
  bucket_path: "docker1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

